### ISSUE TITLE
bug: difference in plugin behavior on iPhone and Android

### ISSUE THREAD

**Issue by Brullworfel** [robingenz/capacitor-screen-orientation#6] opened 2021-07-13 14:51 UTC
**Current behavior:**
Plugin work perfectly on Android, but I cant get it worked on my iPhone.

No errors, just nothing happening.  Promise returns empty.

**AppDelegate.swift**

```swift
import UIKit
import Capacitor
import RobingenzCapacitorScreenOrientation

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

  var window: UIWindow?

  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    return true
  }

func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
    return ScreenOrientation.getSupportedInterfaceOrientations()
  }

  func applicationWillResignActive(_ application: UIApplication) {
  }

...
```

**my.component.ts**

```js
import { ScreenOrientation, OrientationType } from '@robingenz/capacitor-screen-orientation';

...

test_lock(){
    ScreenOrientation.lock({ type: OrientationType.LANDSCAPE }).then(result=>{
      this.toastService.show({message: JSON.stringify(result)}); // <- empty
    }).catch(error=>{
      this.toastService.show({message: JSON.stringify(error), color:'danger'});
    });
}

test_unlock(){
    ScreenOrientation.unlock().then(result=>{
      this.toastService.show({message: JSON.stringify(result)}); // <- empty
    }).catch(error=>{
      this.toastService.show({message: JSON.stringify(error), color:'danger'});
    });
}

...
```

**Capacitor doctor:**

```
Latest Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/ios: 3.1.1

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

Thank you!

**Comment by robingenz** [comment] 2021-07-13 16:20
Thank you for your request.
I will try to reproduce this issue on my test device tomorrow.
Please note that [`lock`](https://github.com/robingenz/capacitor-screen-orientation#lock) and [`unlock`](https://github.com/robingenz/capacitor-screen-orientation#unlock) return `Promise<void>`. So "empty" is the expected result.

**Comment by robingenz** [comment] 2021-07-14 20:12
I can't reproduce the issue with my iPhone 11 (iOS 14.6).
I used the following demo app: [robingenz/capacitor-plugin-demo](https://github.com/robingenz/capacitor-plugin-demo).
Please test the demo app on your device and let me know if the problem persists.

**Comment by Brullworfel** [comment] 2021-07-15 12:35
> I can't reproduce the issue with my iPhone 11 (iOS 14.6).
> I used the following demo app: [robingenz/capacitor-plugin-demo](https://github.com/robingenz/capacitor-plugin-demo).
> Please test the demo app on your device and let me know if the problem persists.

Hello Robin, thank you! I built demo app, launched on my iPhone and got an error when i clicked on "Lock" button:

![IMG_6276](https://user-images.githubusercontent.com/12401672/125788892-df14a4f6-6a50-4dd8-b985-9f3368bf2fbe.PNG)

**Comment by Brullworfel** [comment] 2021-07-15 12:48
I commented out requestFullscreen() call and it's no error now:

```
  public async lock(): Promise<void> {
    //await this.requestFullscreen();
    const currentOrientation = await ScreenOrientation.getCurrentOrientation();
    await ScreenOrientation.lock({ type: currentOrientation.type });
  }
```

But, it not changes orientation. Nothing happens, when I clicked "lock" and "unlock" buttons.

**XCode output:**

```
⚡️  To Native ->  ScreenOrientation getCurrentOrientation 102361273
⚡️  TO JS {"type":"portrait-primary"}
⚡️  To Native ->  ScreenOrientation lock 102361274
⚡️  TO JS undefined
⚡️  To Native ->  ScreenOrientation unlock 102361275
⚡️  TO JS undefined
```

**Comment by robingenz** [comment] 2021-07-15 15:59
Regarding `requestFullscreen()`: You're right! Fixed it with https://github.com/robingenz/capacitor-plugin-demo/commit/340f78de4989473887701b07d625188f5eff3e05.

> But, it not changes orientation. Nothing happens, when I clicked "lock" and "unlock" buttons.

This is the correct behavior when locking the orientation to the current orientation. 🙂 

I just tested it again in the iOS simulator:
1. Rotate the device -> the app rotates too
2. Click on "Lock
3. Rotate the device -> the app does not rotate

For this reason, I am now closing this issue. Please let me know if you still have problems. I will try to help as good as I can.

**Comment by Brullworfel** [comment] 2021-07-15 16:04
Sorry, Robert, but lock() on Android rotates screen and locks it. On iPhone it does not rotate screen.

**Comment by robingenz** [comment] 2021-07-15 17:00
Are you sure you had the current orientation selected on Android?
The screen should rotate to the specified orientation.
However, if you specify the current orientation, it will only lock and not rotate.
Please test the demo app on Android as well to make sure you are using the same code to test on both platforms.

**Comment by Brullworfel** [comment] 2021-07-16 08:05
Robert, thanks for your patience)

On Android, when I call the lock() function with the "landscape" parameter, the screen automatically rotates to the specified position and locks. Then, when I call unlock (), the screen returns to the position corresponding to the real position of the device. This is exactly the behavior I need.

On the iPhone, when I call lock() with the "landscape" parameter, the screen does not rotates automatically, and nothing visible happens at all. However, when I rotate the device horizontally myself, the screen rotates and then locks in the landscape position. Then, after calling unlock (), the screen can rotates to a different position.

I need it to work the same way on the iPhone as it does now on Android, so that I can force the screen to the specified position.

iPhone behavior video: https://youtu.be/cxWKYMPFQP8
Android behavior video: https://youtu.be/y1KnmKvoYqQ

Test app on the video: https://github.com/Brullworfel/capacitor-screen-orientation-test

Thank you!

**Comment by robingenz** [comment] 2021-07-16 12:35
Okay, now I got it!
I will have a look at it.
Thanks for the examples.

**Comment by robingenz** [comment] 2021-07-16 17:23
I fixed the issue that the screen does not rotate on iOS when it is locked.
Unfortunately, I couldn't find a way to rotate the screen to the current orientation after unlocking, since I don't know the "correct" current orientation at this point.
Android, for example, offers a constant specifically for this purpose.
I'm not sure if this is currently possible on iOS, but I hope to find a solution in the future. Any hints are welcome.

**Closed** 2021-07-16 17:34 UTC
Labels: bug/fix

**Comment by Brullworfel** [comment] 2021-07-18 06:53
> I fixed the issue that the screen does not rotate on iOS when it is locked.

Hello Robert!

Sorry Robert, but I updated the plugin and nothing has changed in the behavior on the iPhone.

Please, check it: https://github.com/robingenz/capacitor-screen-orientation

**Comment by robingenz** [comment] 2021-07-18 11:12
I just tried your app again and it worked fine for me (iPhone 11, iOS 14.6).
Please make sure that there are no files cached by XCode.
I have done the following steps:
1. Clone https://github.com/Brullworfel/capacitor-screen-orientation-test
1. `npm i`
1. `npx ionic cap sync ios`
2. `npx ionic cap run ios --open`

**Comment by Brullworfel** [comment] 2021-07-18 13:56
You are right, it was XCode issue. Works great now, thank you!
